config/routes.rb
AppSys::Application.routes.draw do

  root to: 'page#home'
	get 'home' => 'page#home'
  get 'contact' => 'page#contact'
	get 'signup' => 'applicants#new'
	get 'login' => 'sessions#new'
	get 'requirementsc' => 'page#requirementsc'
  get 'requirementsp' => 'page#requirementsp'
  get 'requirementsv' => 'page#requirementsv'
  get 'resources' => 'page#resources'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'

	resources :applicants do
		collection do
			get 'search'
		end
		resources :volunteers do
			member do
				put 'change_status'
			end
		end
		resources :internships do
			member do
				put 'change_status'
			end
		end
	end
	resources :volunteers
	resources :internships
	resources :account_activations, only: [:edit]
	resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  belongs_to :applicant
  #attr_accessible :title, :body
  attr_protected
  
  VALID_DOB_REGEX=/^\d{2}\/\d{2}\/\d{4}$/i
  validates :date_of_birth, format: {with: VALID_DOB_REGEX}
  VALID_EMAIL_REGEX= /\A[\w\.\-]+\@[a-z\d\.\-]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, 
						format: {with: VALID_EMAIL_REGEX}
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController

	before_filter :logged_in_user
	before_filter :correct_user, only: [:edit, :update, :destroy]
	before_filter :correct_or_admin, only: [:show]

	require 'will_paginate/array'
	
	def show
		@applicant=Applicant.where(id: params[:applicant_id]).first
		@volunteer=@applicant.volunteers.where(id: params[:id]).first	
		@type=params[:type]	
		@mode=params[:mode]
	end
	
	def new
		@applicant=current_user
		@volunteer=@applicant.volunteers.new
		@type=params[:type]
	end
	
	def create
		@applicant=current_user
		@volunteer=@applicant.volunteers.new(params[:volunteer])
		@type=params[:type]
		if @volunteer.save
			render '_general_information'
		else
			render 'new'
		end		
	end
	
	def edit
		@applicant=Applicant.where(id: params[:applicant_id]).first
		@volunteer=@applicant.volunteers.where(id: params[:id]).first
		@type=params[:type]
		render 'new'
	end
	
	def update
		@applicant=current_user
		step=params[:step].to_i
		@volunteer=@applicant.volunteers.where(id: params[:volunteer_id]).first
		@type=params[:type]
				if @volunteer.update_attributes(params[:volunteer])
					case step
					when 0
						render 'new'
					when 1
						render '_general_information'
					when 2
						render '_experience'
					when 3
						render '_skills_special_ability'
					when 4
						render '_emergency_notification'
					when 5
						flash[:success]=["Application created/updated.","You can view/edit/delete your application before submission."]
						redirect_to @applicant
					end
				else
					case step
					when 1
						render 'new'
					when 2
						render '_general_information'
					when 3
						render '_experience'
					when 4
						render '_skills_special_ability'
					when 5
						render '_emergency_notification'
					end
				end
		
	end
	
	def destroy
		Volunteer.find(params[:id]).destroy
		flash[:success]="Successfully deleted."
		redirect_to current_user
	end
	
	def index
		@type=params[:type]
		@volunteers=Volunteer.all.paginate(page: params[:page], per_page: 15)
	end
	
	def change_status
		@applicant=current_user
		@volunteer=@applicant.volunteers.where(id: params[:id]).first
		ApplicantMailer.volunteer_notification(@applicant,@volunteer).deliver
		ApplicantMailer.volunteer_confirmation(@applicant,@volunteer).deliver
		@volunteer.update_attributes(params[:status])
		flash[:success]=["Application form submited!","To finish your application, please also complete:", "Pledge of Confidentiality.pdf", "Non-disclosure Form.pdf", "Reference Form.pdf", "which can be found in Resouces tab above and send them to info@scottyshouse.org"]
		redirect_to current_user
	end
	
	def logged_in_user
		unless logged_in?
			store_location
			flash[:danger]="You need to log in."
			redirect_to login_url
		end
	end
	
	def correct_user
		@volunteer=Volunteer.where(id: params[:id]).first
		unless current_user?(@volunteer.applicant)
			flash[:danger]="Authorization limited."
			redirect_to(root_url)			
		end
	end
	
	def correct_or_admin
		@volunteer=Volunteer.where(id: params[:id]).first
		unless ( current_user?(@volunteer.applicant) || current_user.is_admin? )
			flash[:danger]="Authorization limited."
			redirect_to(root_url)			
		end
	end
	
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/volunteers/_emergency_notification.html.erb
<h1>Emergency Notification</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 ">
    <%= form_for(@volunteer) do |f| %>
			<%= render 'shared/error_messages' %>

      <%= f.label :emergency_name, "Name" %>
      <%= f.text_field :emergency_name, class: 'form-control' %>
      
      <%= f.label :emergency_phone, "Phone number" %>
      <%= f.text_field :emergency_phone, class: 'form-control' %>
      
      <%= f.label :emergency_address, "Address" %>
      <%= f.text_field :emergency_address, class: 'form-control' %>
      
      <%= f.label :emergency_relation, "Relationship" %>
      <%= f.text_field :emergency_relation, class: 'form-control' %>
			
			<%= hidden_field_tag :volunteer_id, @volunteer.id %>

      <%= f.button  :Previous, name: "step",value: "3", class: "btn btn-warning col-md-2 col-md-offset-3"%>      
      <div></div>
      <%= f.button :Finish, name: "step",value: "5", class: "btn btn-primary col-md-2 col-md-offset-2" %>
		<% end %>
  </div>
</div>

app/views/volunteers/_experience.html.erb
<h1>Experience</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 ">
    <%= form_for(@volunteer) do |f| %>
			<%= render 'shared/error_messages' %>
			
			<%= f.label :experience, "Please list any previous Volunteer experience, particularly in working with children and families:" %>
      <%= f.text_area :experience, class: 'form-control', rows: 10,placeholder: "Length of time | Organization | Responsibilities" %>
      
      <p>Do you have any experience with:</p>
      <%= f.label :child_abuse do %>
      	<%= f.check_box :child_abuse, class: "checkbox-auto" %>
      	<span>Child abuse?</span>
      <% end %>
      <%= f.label :child_abuse_spec, "If yes, please explain: " %>
      <%= f.text_area :child_abuse_spec, class: 'form-control', rows: 5 %>
      
      <%= f.label :foster_care do %>
      	<%= f.check_box :foster_care, class: "checkbox-auto" %>
      	<span>Foster care?</span>
      <% end %>
      <%= f.label :foster_care_spec, "If yes, please explain: " %>
      <%= f.text_area :foster_care_spec, class: 'form-control', rows: 5 %>      
           
      <%= f.label :criminal do %>
      	<%= f.check_box :criminal, class: "checkbox-auto" %>
      	<span>Criminal, Juvenile or Family Court System? </span>
      <% end %>
      <%= f.label :crinimal_spec, "If yes, please explain: " %>
      <%= f.text_area :crinimal_spec, class: 'form-control', rows: 5 %>
      
      <%= f.label :other_service do %>
      	<%= f.check_box :other_service, class: "checkbox-auto" %>
      	<span>Other Child Service Agencies? </span>
      <% end %>
      <%= f.label :other_service_spec, "If yes, please explain: " %>
      <%= f.text_area :other_service_spec, class: 'form-control', rows: 5 %>
			
			<%= hidden_field_tag :volunteer_id, @volunteer.id %>

      <%= f.button  :Previous, name: "step",value: "1", class: "btn btn-warning col-md-2 col-md-offset-3"%>      
      <div></div>
      <%= f.button :Next, name: "step",value: "3", class: "btn btn-primary col-md-2 col-md-offset-2" %>
		<% end %>
  </div>
</div>

app/views/volunteers/_general_information.html.erb
<h1>General Information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 ">
    <%= form_for(@volunteer) do |f| %>
			<%= render 'shared/error_messages' %>
			
			<%= f.label :how_learn_about, "How did you learn about Scotty’s House and our Volunteer Program?" %>
      <%= f.text_area :how_learn_about, class: 'form-control', rows: 5 %>
      
      <%= f.label :what_to_gain, "What would you like to gain from your Volunteer experience?" %>
      <%= f.text_area :what_to_gain, class: 'form-control', rows: 5 %>
      
      <p>Are you volunteering for:</p>
      <%= f.label :class_credit do %>
      	<%= f.check_box :class_credit, class: "checkbox-auto" %>
      	<span>Class Credit (Please provide the name of your Instructor.)</span>
      <% end %>
      <%= f.text_field :instructor_name, class: 'form-control' %>
      
      <%= f.label :organization_credit do %>
      	<%= f.check_box :organization_credit, class: "checkbox-auto" %>
      	<span>Organization Credit (Please provide the name of your Organization.)</span>
      <% end %>
      <%= f.text_field :organiztion_name, class: 'form-control' %>
      
      <%= f.label :organiztion_name do %>
      	<%= f.check_box :organiztion_name, class: "checkbox-auto" %>
      	<span>Other (Please explain.)</span>
      <% end %>
			<%= f.text_field :other_spec, class: 'form-control' %>
			
			<p>Are you currently employed?</p>
			<%= f.label :employed do %>
      	<%= f.check_box :employed, class: "checkbox-auto" %>
      	<span>Currently employed (Name of employer)</span>
      <% end %>
			<%= f.text_field :employer_name, class: 'form-control' %>
			
			<%= hidden_field_tag :volunteer_id, @volunteer.id %>
			<%= hidden_field_tag :type, @type %>

      <%= f.button  :Previous, name: "step",value: "0", class: "btn btn-warning col-md-2 col-md-offset-3"%>      
      <div></div>
      <%= f.button :Next, name: "step",value: "2", class: "btn btn-primary col-md-2 col-md-offset-2" %>
		<% end %>
  </div>
</div>

app/views/volunteers/_skills_special_ability.html.erb
<h1>Skills & Special Abilities</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 ">
    <%= form_for(@volunteer) do |f| %>
			<%= render 'shared/error_messages' %>

      <%= f.label :speak do %>
      	<%= f.check_box :speak, class: "checkbox-auto" %>
      	<span>Do you speak any language other than English?</span>
      <% end %>
      <div class="clearfix"></div>
      <%= f.label :speak_what, "If yes, what language? " %>
      <%= f.text_field :speak_what, class: 'form-control' %>
      
      <%= f.label :read do %>
      	<%= f.check_box :read, class: "checkbox-auto" %>
      	<span>Do you read/write in any language other than English?</span>
      <% end %>
      <div class="clearfix"></div>
      <%= f.label :read_what, "If yes, what language? " %>
      <%= f.text_field :read_what, class: 'form-control' %>
      
      <%= f.label :blind do %>
      	<%= f.check_box :blind, class: "checkbox-auto" %>
      	<span>Do you have any experience with blind or hearing impaired persons?</span>
      <% end %>
      <div class="clearfix"></div>
      <%= f.label :blind_experience, "In what capacity? " %>
      <%= f.text_field :blind_experience, class: 'form-control' %>
      
      <%= f.label :handicap do %>
      	<%= f.check_box :handicap, class: "checkbox-auto" %>
      	<span>Do you have any experience with handicapped persons?</span>
      <% end %>
      <div class="clearfix"></div>
      <%= f.label :handicap_experience, "In what capacity? " %>
      <%= f.text_field :handicap_experience, class: 'form-control' %>
			
			<%= hidden_field_tag :volunteer_id, @volunteer.id %>

      <%= f.button  :Previous, name: "step",value: "2", class: "btn btn-warning col-md-2 col-md-offset-3"%>      
      <div></div>
      <%= f.button :Next, name: "step",value: "4", class: "btn btn-primary col-md-2 col-md-offset-2" %>
		<% end %>
  </div>
</div>

app/views/volunteers/_volunteer.html.erb
<li class="list-group-item container">
	
	 <% time=volunteer.created_at.strftime("%d %b %Y")+":" %>
	 <% application='' %>
	 <% if volunteer.family_care %>
		<% application += " Family Care," %>
	 <% end %>
	 <% if volunteer.medical_volunteer %>
		<% application += " Medical Volunteer," %>
	 <% end %>
	 <% if volunteer.ambassador %>
		<% application += " Ambassador," %>
	 <% end %>
	 <% if volunteer.prevention_volunteer %>
		<% application += " Prevention Volunteer," %>
	 <% end %>
	 <% if volunteer.additional_volunteer_opportunity %>
		<% application += " Additional Volunteer Opportunity," %>
	 <% end %>
	 <% if volunteer.pragram_internship %>
		<% application += " Program Internship" %>
	 <% else%>
	  <% application=application[0...-1] %>
	  <% application += " (Volunteer)" %>
	 <% end %>
	 <span><%= time %></span>
	 <span><%= application %></span>
	 <div></div>
	 <% if volunteer.pragram_internship? %>
	 	<% type="program" %>
	 <% else %>
	 	<% type="volunteer" %>
	 <% end%>
	 <%= link_to "View", applicant_volunteer_path(@applicant, volunteer, mode: "#{@mode}") %>
	 <% if !current_user.nil? && !current_user.admin? && current_user?(@applicant) && !volunteer.submited%>
	 	 | <%= link_to "Edit", edit_applicant_volunteer_path(@applicant, volunteer, type: "#{type}") %> 
	 	 | <%= link_to "Delete", applicant_volunteer_path(@applicant, volunteer), method: :delete, data: {confirm: "Are you sure?"} %>
	 	 <%= link_to "Submit", change_status_applicant_volunteer_path(@applicant, volunteer, status: {submited: true}), method: :put, class: 'pull-right btn btn-warning' %>
	 <% end %>
	
</li>

app/views/volunteers/_volunteer_application.html.erb
<h1>Volunteer Application</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 ">
    <%= form_for(@volunteer) do |f| %>
			<%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :date_of_birth, "Date of Birth(MM/DD/YYYY)" %>
      <%= f.text_field :date_of_birth, class: 'form-control' %>

      <%= f.label :email, "Email Address"%>
      <%= f.email_field :email , class: 'form-control'%>
      
      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control' %>
      
      <%= f.label :mailing_address, "Mailing Address" %>
      <%= f.text_field :mailing_address, class: 'form-control' %>

      <p>Scotty’s House Child Advocacy Center has several opportunities for Volunteers. All types of volunteers are needed to make services available to families in our community, and we value any skills you may have to help us improve the community in which we live. Listed below are the current Volunteer Opportunities available at Scotty’s House. Please check the areas in which you are most interested:</p>
      
   
      <%= f.label :family_care, class: "col-md-6" do %>
      	<%= f.check_box :family_care, class: "checkbox-auto" %>
      	<span>Family Care</span>
      <% end %>
      
   		<%= f.label :medical_volunteer, class:"col-md-6" do %>
      	<%= f.check_box :medical_volunteer, class: "checkbox-auto" %>
      	<span>Medical Volunteer</span>
      <% end %>
     
      
      <%= f.label :ambassador, class:"col-md-6" do %>
      	<%= f.check_box :ambassador, class: "checkbox-auto" %>
      	<span>Ambassador</span>
      <% end %>   
      
      <%= f.label :pragram_internship, class:"col-md-6" do %>
      	<%= f.check_box :pragram_internship, class: "checkbox-auto" %>
      	<span>Program/Counseling Internship</span>
      <% end %>   
      
      <%= f.label :prevention_volunteer, class:"col-md-6" do %>
      	<%= f.check_box :prevention_volunteer, class: "checkbox-auto" %>
      	<span>Prevention Volunteer</span>
      <% end %>   
      
      <%= f.label :additional_volunteer_opportunity, class:"col-md-6" do %>
      	<%= f.check_box :additional_volunteer_opportunity, class: "checkbox-auto" %>
      	<span>Additional Volunteer Opportunities*</span>
      <% end %>  
      
      <%= f.label :additional_volunteer_opportunity_spec, "*If you have selected Additional Volunteer Opportunities, please specify:" %>
      <%= f.text_field :additional_volunteer_opportunity_spec, class: 'form-control' %>
      
      <%= f.label :days_available, "Days/Times you will be available to Volunteer:" %>
      <%= f.text_field :days_available, class: 'form-control' %>
      
      <%= hidden_field_tag :step, 1 %>
      
      <%= hidden_field_tag :volunteer_id, @volunteer.id %>

      <%= f.submit "Next", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/volunteers/create.html.erb
<p>?</p>

app/views/volunteers/index.html.erb
<h1><% if @type=="volunteer"%>
		Volunteer 
	<% else %>
		Program Intern 
	<% end %>
	Applications List
</h1>

<div class="volunteers col-sm-offset-3 col-sm-6"><%= will_paginate %></div>

<ul class="volunteers col-sm-offset-3 col-sm-6"> 
	
	<% @volunteers.each do |volunteer| %> 
		<% if @type=="volunteer" && volunteer.pragram_internship %>
			<% next %>
		<% elsif @type=='program' && !volunteer.pragram_internship %>
			<% next %>
		<% end %>
		<li class="list-group-item">
			 <% time=volunteer.created_at.strftime("%d %b %Y")+":" %>
			 <% application='' %>
			 
				<% if @type=="volunteer"%>
				 <% if volunteer.family_care %>
					<% application += " Family Care," %>
				 <% end %>
				 <% if volunteer.medical_volunteer %>
					<% application += " Medical Volunteer," %>
				 <% end %>
				 <% if volunteer.ambassador %>
					<% application += " Ambassador," %>
				 <% end %>
				 <% if volunteer.prevention_volunteer %>
					<% application += " Prevention Volunteer," %>
				 <% end %>
				 <% if volunteer.additional_volunteer_opportunity %>
					<% application += " Additional Volunteer Opportunity," %>
				 <% end %>	
				 <% application=application[0...-1] %>
			 	 <% application += " (Volunteer)" %> 
			 	<% else %>
				 <% if volunteer.pragram_internship %>
					<% application += " Program Internship" %>
				 <% end%>
				<% end %>
			 
			 <div style="font-size: 1.8em; ">Applicant: <span class="text-primary"><%= volunteer.name %></span></div>
			 <div style="font-size: 1.2em;" class="text-primary"><%= time %></div>
			 <div style="font-size: 1.2em;" class="text-success"><%= application %></div>
			 <% if @type=="volunteer" %>
					<%= link_to "View", applicant_volunteer_path(volunteer.applicant, volunteer,type: "volunteer"), class: "btn bg-primary " %>
				<% elsif @type=='program' %>
					<%= link_to "View", applicant_volunteer_path(volunteer.applicant, volunteer,type: "program"), class: "btn bg-primary " %>
				<% end %>
		</li>
	<% end %>
	<br>
	<div class="center"><%= link_to "Go back", applicant_path(current_user), class: "btn btn-lg btn-primary" %></div>
</ul>

app/views/volunteers/new.html.erb
<% if @type=="volunteer"%>
	<% show="shown"%>
	<% type="Volunteer "%>
<% else %>
	<% show="not-shown"%>
	<% type="Program Intern" %>
<% end %>

<h1><%= type %> Application
</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 ">
    <%= form_for(@volunteer) do |f| %>
			<%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :date_of_birth, "Date of Birth(MM/DD/YYYY)" %>
      <%= f.text_field :date_of_birth, class: 'form-control' %>

      <%= f.label :email, "Email Address"%>
      <%= f.email_field :email , class: 'form-control'%>
      
      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control' %>
      
      <%= f.label :mailing_address, "Mailing Address" %>
      <%= f.text_field :mailing_address, class: 'form-control' %>


      <div id="<%= show %>">
      <p>Scotty’s House Child Advocacy Center has several opportunities for Volunteers. All types of volunteers are needed to make services available to families in our community, and we value any skills you may have to help us improve the community in which we live. Listed below are the current Volunteer Opportunities available at Scotty’s House. Please check the areas in which you are most interested:</p>
      
   
      <%= f.label :family_care, class: "col-md-6" do %>
      	<%= f.check_box :family_care, class: "checkbox-auto" %>
      	<span>Family Care</span>
      <% end %>
      
   		<%= f.label :medical_volunteer, class:"col-md-6" do %>
      	<%= f.check_box :medical_volunteer, class: "checkbox-auto" %>
      	<span>Medical Volunteer</span>
      <% end %>
     
      
      <%= f.label :ambassador, class:"col-md-6" do %>
      	<%= f.check_box :ambassador, class: "checkbox-auto" %>
      	<span>Ambassador</span>
      <% end %>    
      
      <%= f.label :prevention_volunteer, class:"col-md-6" do %>
      	<%= f.check_box :prevention_volunteer, class: "checkbox-auto" %>
      	<span>Prevention Volunteer</span>
      <% end %>   
      
      <%= f.label :additional_volunteer_opportunity, class:"col-md-6" do %>
      	<%= f.check_box :additional_volunteer_opportunity, class: "checkbox-auto" %>
      	<span>Additional Volunteer Opportunities*</span>
      <% end %>  
      
      <%= f.label :additional_volunteer_opportunity_spec, "*If you have selected Additional Volunteer Opportunities, please specify:" %>
      <%= f.text_field :additional_volunteer_opportunity_spec, class: 'form-control' %>
      
      <%= f.check_box :pragram_internship, {checked: true} if @type=="program"%>
      </div>
      
      <%= f.label :days_available, "Days/Times you will be available to Volunteer (MM/DD/YYYY-MM/DD/YYYY):" %>
      <%= f.text_field :days_available, class: 'form-control' %>
      
      <%= hidden_field_tag :step, 1 %>
      <%= hidden_field_tag :type, @type %>
      <%= hidden_field_tag :volunteer_id, @volunteer.id %>
      <%= hidden_field_tag :type, @type %>

      <%= f.submit "Next", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/volunteers/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 ">

<h1>Application Summary</h1>

<p>Date of Application: <span><%= @volunteer.created_at.strftime("%d %b. %Y") %></span></p>
<p> Name: <span><%= @volunteer.name %></span></p>
<p> Date of Birth: <span><%= @volunteer.date_of_birth %></span></p>
<p> Email address: <span><%= @volunteer.email %></span></p>
<p> Phone number: <span><%= @volunteer.phone %></span></p>
<p> Mailing address: <span><%= @volunteer.mailing_address %></span></p>
<p>Scotty’s House Child Advocacy Center has several opportunities for Volunteers. All types of volunteers are needed to make services available to families in our community, and we value any skills you may have to help us improve the community in which we live. Listed below are the current Volunteer Opportunities available at Scotty’s House. Please check the areas in which you are most interested:</p>
<% if @volunteer.family_care %>
	<p class="bold">Family Care</p>
<% end %>
<% if @volunteer.medical_volunteer %>
	<p class="bold">Medical Volunteer</p>
<% end %>
<% if @volunteer.ambassador %>
	<p class="bold">Ambassador</p>
<% end %>
<% if @volunteer.pragram_internship %>
	<p class="bold">Program Internship</p>
<% end %>
<% if @volunteer.prevention_volunteer %>
	<p class="bold">Prevention Volunteer</p>
<% end %>
<% if @volunteer.additional_volunteer_opportunity %>
	<p class="bold">Additional Volunteer Opportunities*</p>
	<p>*If you have selected Additional Volunteer Opportunities, please specify:</p>
	<p class="bold"><%= @volunteer.additional_volunteer_opportunity_spec %></p>
<% end %>
<p> Days/Times you will be available to Volunteer: <span><%= @volunteer.days_available %></span></p>




<h1>General Information</h1>
<p> How did you learn about Scotty’s House and our Volunteer Program? </p>
<p class="bold"><%= @volunteer.how_learn_about %></p>
<p> What would you like to gain from your Volunteer experience? </p>
<p class="bold"><%= @volunteer.what_to_gain %></p>
<p>Are you volunteering for:</p>
<% if @volunteer.class_credit %>
	<p>Class Credit (Please provide the name of your Instructor.)</p>
	<p class="bold"><%= @volunteer.instructor_name%></p>
<% end %>
<% if @volunteer.organization_credit %>
	<p>Organization Credit (Please provide the name of your Organization.)</p>
	<p class="bold"><%= @volunteer.organiztion_name%></p>
<% end %>
<% if @volunteer.other %>
	<p >Other (Please explain.)</p>
	<p class="bold"><%= @volunteer.other_spec%></p>
<% end %>
<% if @volunteer.employed %>
	<p>Name of employer</p>
	<p class="bold"><%= @volunteer.employer_name %></p>
<% end %>



<h1>Experience</h1>
<p>Please list any previous Volunteer experience, particularly in working with children and families:</p>
<p class="bold"><%= @volunteer.experience%></p>
<p>Do you have any experience with:</p>
<% if @volunteer.child_abuse %>
	<p class="bold">Child abuse</p>
	<p><%= @volunteer.child_abuse_spec%></p>
<% end %>
<% if @volunteer.foster_care %>
	<p class="bold">Foster care</p>
	<p><%= @volunteer.foster_care_spec%></p>
<% end %>
<% if @volunteer.criminal %>
	<p class="bold">Criminal, Juvenile or Family Court System</p>
	<p><%= @volunteer.crinimal_spec%></p>
<% end %>
<% if @volunteer.other_service %>
	<p class="bold">Other Child Service Agencies</p>
	<p><%= @volunteer.other_service_spec%></p>
<% end %>


<h1>Skills and Special Abilities</h1>
<% if @volunteer.speak %>
	<p>Do you speak any language other than English?</p>
	<p class="bold"><%= @volunteer.speak_what%></p>
<% end %>
<% if @volunteer.read %>
	<p>Do you read/write in any language other than English?</p>
	<p class="bold"><%= @volunteer.read_what%></p>
<% end %>
<% if @volunteer.blind %>
	<p>Do you have any experience with blind or hearing impaired persons?</p>
	<p class="bold"><%= @volunteer.blind_experience%></p>
<% end %>
<% if @volunteer.handicap %>
	<p>Do you have any experience with handicapped persons?</p>
	<p class="bold"><%= @volunteer.handicap_experience%></p>
<% end %>



<h1>Emergency Notification</h1>
<p>Name</p>
<p class="bold"><%= @volunteer.emergency_name%></p>
<p>Phone number</p>
<p class="bold"><%= @volunteer.emergency_phone%></p>
<p>Address</p>
<p class="bold"><%= @volunteer.emergency_address%></p>
<p>Relationship</p>
<p class="bold"><%= @volunteer.emergency_relation%></p>

		<% if current_user.admin? && @mode!="review" %>
			<div class="center"><%= link_to "Go back", volunteers_path(type: "#{@type}"), class: "btn btn-lg btn-primary" %></div>
		<% else %>
			<div class="center"><%= link_to "Go back", applicant_path(@applicant), class: "btn btn-lg btn-primary" %></div>
		<% end %>

	</div>
</div>