config/routes.rb
AppSys::Application.routes.draw do

  root to: 'page#home'
	get 'home' => 'page#home'
  get 'contact' => 'page#contact'
	get 'signup' => 'applicants#new'
	get 'login' => 'sessions#new'
	get 'requirementsc' => 'page#requirementsc'
  get 'requirementsp' => 'page#requirementsp'
  get 'requirementsv' => 'page#requirementsv'
  get 'resources' => 'page#resources'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'

	resources :applicants do
		collection do
			get 'search'
		end
		resources :volunteers do
			member do
				put 'change_status'
			end
		end
		resources :internships do
			member do
				put 'change_status'
			end
		end
	end
	resources :volunteers
	resources :internships
	resources :account_activations, only: [:edit]
	resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/applicant.rb
class Applicant < ActiveRecord::Base

	has_many :volunteers
	has_many :internships
  attr_accessible :email, :name, :password, :password_confirmation, :remember_digest, :admin, :activation_digest, :activated, :activated_at, :reset_digest, :reset_sent_at
  attr_accessor :remember_token, :activation_token, :reset_token
	before_save :downcase_email
	before_create :create_activation_digest
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX= /\A[\w\.\-]+\@[a-z\d\.\-]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, 
						format: {with: VALID_EMAIL_REGEX},
						uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, length:{minimum: 6}, allow_blank: true

	def downcase_email
		self.email=email.downcase
	end
	
	def create_activation_digest
		self.activation_token=Applicant.new_token
		self.activation_digest=Applicant.digest(activation_token)
	end
	
	private :downcase_email, :create_activation_digest
		
	def Applicant.digest(string)
    cost =  BCrypt::Engine::MIN_COST #todo: no min_cost error
    BCrypt::Password.create(string, cost: cost)
  end
  
  def Applicant.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
  	self.remember_token=Applicant.new_token
  	update_attribute(:remember_digest,Applicant.digest(remember_token))
  end
  
  def authenticated?(attribute, token)
  	digest=send("#{attribute}_digest")
  	return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  def forget
  	update_attribute(:remember_digest, nil)
  end
  
  def is_admin?
  	return false if self.nil?
  	self.admin?
  end
  
  def activate
  	update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end
  
  def send_activation_email
  	ApplicantMailer.account_activation(self).deliver
  end
  
  def create_reset_digest
    self.reset_token = Applicant.new_token
    update_attribute(:reset_digest,  Applicant.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end
  
  def send_password_reset_email
    ApplicantMailer.password_reset(self).deliver
  end
  
  def password_reset_expired?
  	reset_sent_at < 2.hours.ago
  end
  
  def self.search(applicant)
  	applicants=where(activated: true)
  	by_name=applicants.where("name like ?", "%#{applicant}%") 
  	by_email=applicants.where("email like ?", "%#{applicant}%")
  	by_name+by_email
  end
  
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController

	before_filter :logged_in_user, only: [:show, :edit, :update, :index, :destroy]
	before_filter :correct_user, only: [:edit, :update]
	before_filter :admin_user, only: [:index, :destroy]
	before_filter :correct_or_admin, only: [:show]

  def new
		@applicant=Applicant.new
  end

	def show
		@applicant=Applicant.find(params[:id])
		@volunteers=@applicant.volunteers.all
		@internships=@applicant.internships.all
		if current_user.admin?
			@mode="review"
		end
		redirect_to root_url and return unless @applicant.activated?
	end

	def create
		@applicant=Applicant.new(applicant_params)
		if @applicant.save
			#log_in @applicant
			#flash[:success]="Account created successfully!"
			#redirect_to @applicant
			@applicant.send_activation_email
			flash[:info]="Please check your email to activate your account"
			redirect_to root_url
		else
			render 'new'
		end
	end
	
	def edit
		@applicant=Applicant.find(params[:id])
	end
	
	def update
		@applicant=Applicant.where(id: params[:id]).first
		if @applicant.update_attributes(applicant_params)
			flash[:success]="Information updated successfully!"
			redirect_to @applicant
		else
			render 'edit'
		end
	end
	
	def destroy
		Applicant.find(params[:id]).destroy
		flash[:success]="Successfully deleted."
		redirect_to applicants_url
	end
	
	def index
		@applicants=Applicant.where(activated: true).paginate(page: params[:page], per_page: 15)
	end
	
	def search
		@applicants=Applicant.search(params[:search]).uniq;
	end

	private
		def applicant_params
			params.require(:applicant).permit(:name, :email, :password, :password_confirmation)
		end
		
	def logged_in_user
		unless logged_in?
			store_location
			flash[:danger]="You need to log in."
			redirect_to login_url
		end
	end
	
	def correct_user
		@applicant=Applicant.where(id: params[:id]).first
		unless current_user?(@applicant)
			flash[:danger]="Authorization limited."
			redirect_to(root_url)			
		end
	end
	
	def admin_user
		unless current_user.is_admin?
			flash[:danger]="Authorization limited."
			redirect_to(root_url)			
		end
	end
	
	def correct_or_admin
		@applicant=Applicant.where(id: params[:id]).first
		unless ( current_user?(@applicant) || current_user.is_admin? )
			flash[:danger]="Authorization limited."
			redirect_to(root_url)			
		end
	end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
	def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/applicants/_applicant.html.erb
<li>
	
	 <%= gravatar_for applicant, size: 50 %>
	 <%= link_to applicant.name, applicant_path(applicant, mode: "review") %>
	 <% if !current_user.nil? && current_user.admin? && !current_user?(applicant)%>
	 	 | <%= link_to "Delete", applicant, method: :delete, data: {confirm: "Are you sure?"} %>
	 <% end %>
	
</li>

app/views/applicants/edit.html.erb
<h1>Update Information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 ">
  	<div class="gravatar_edit row">
      <%= gravatar_for @applicant %>
      <a href="http://gravatar.com/emails" target=_blank class="btn btn-primary">Change</a>
    </div>
  
    <%= form_for(@applicant) do |f| %>
			<%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email , class: 'form-control'%>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>    
    
  </div>
</div>

app/views/applicants/index.html.erb
<h1>Applicants List</h1>

<%= will_paginate %>

<ul class="applicants"> 
	<%= render @applicants %>    
</ul>

<%= will_paginate %>

<br>
<div class="center"><%= link_to "Go back", applicant_path(current_user), class: "btn btn-lg btn-primary" %></div>

app/views/applicants/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 ">
    <%= form_for(@applicant) do |f| %>
			<%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email , class: 'form-control'%>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/applicants/search.html.erb
<h1>Search Results</h1>

<ul class="applicants"> 
	<%= render @applicants %>    
</ul>

app/views/applicants/show.html.erb
<div class="col-md-4 " >
		<h1>
       <%= gravatar_for @applicant %>
       <div><%= @applicant.name %></div>
       <div id="show_email"><%= @applicant.email %><div>
     </h1>
</div>

<div class="col-md-1"></div>  


<div class="col-md-7">
	<% if @applicant.admin? %>
		<div class="center">
			<p style="font-size:2.6em; margin-top:20px;">Administrator Interface</p>
			<p style="font-size:2em;"><%= link_to "View all applicants", applicants_path %></p>
			<p style="font-size:2em;"><%= link_to "View all counselling intern applications", internships_path %></p>
			<p style="font-size:2em;"><%= link_to "View all volunteer applications", volunteers_path(type: "volunteer") %></p>
			<p style="font-size:2em;"><%= link_to "View all program intern applications", volunteers_path(type: "program") %></p>
			<%= form_tag(search_applicants_path, method: "get", class: "form-inline") do %>
				<label>Search Applicants</label>
				<div class="form-group">
					<div class="input-group">
						<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Enter name or email" %>
					</div>
				</div>
				<button class="btn btn-primary" type="submit">Search</button>
			<% end %>
		</div>
	<% else %>
		<div class="jumbotron">

		<h1 style="font-size: 3.5em;">My applications</h1>
		<% if @applicant.internships.first.nil? && @applicant.volunteers.first.nil? %>
			<p id="none" class="center">None</p>
		<% end %>
		
		<ul class="internships"> 
			<%= render @internships %>    
		</ul>
				
		<ul class="volunteers"> 
			<%= render @volunteers %>    
		</ul>
		
		<% unless current_user.admin? %>
		<div class="center"><%= link_to "New Counseling Intern Application", new_applicant_internship_path(@applicant), class: "btn btn-lg btn-primary", id: "add-top" %></div>
		<div class="center"><%= link_to "New Volunteer Application", new_applicant_volunteer_path(@applicant, type: "volunteer"), class: "btn btn-lg btn-info", id: "add-top" %></div>
		<div class="center"><%= link_to "New Program Intern Application", new_applicant_volunteer_path(@applicant, type: "program"), class: "btn btn-lg btn-success", id: "add-top" %></div>
		<% end %>
		</div>
	<% end %>
</div>  