config/routes.rb
AppSys::Application.routes.draw do

  root to: 'page#home'
	get 'home' => 'page#home'
  get 'contact' => 'page#contact'
	get 'signup' => 'applicants#new'
	get 'login' => 'sessions#new'
	get 'requirementsc' => 'page#requirementsc'
  get 'requirementsp' => 'page#requirementsp'
  get 'requirementsv' => 'page#requirementsv'
  get 'resources' => 'page#resources'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'

	resources :applicants do
		collection do
			get 'search'
		end
		resources :volunteers do
			member do
				put 'change_status'
			end
		end
		resources :internships do
			member do
				put 'change_status'
			end
		end
	end
	resources :volunteers
	resources :internships
	resources :account_activations, only: [:edit]
	resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/internship.rb
class Internship < ActiveRecord::Base
  belongs_to :applicant
  # attr_accessible :title, :body
  attr_protected
  
  validates :name, presence: true
end

app/controllers/internships_controller.rb
class InternshipsController < ApplicationController

	before_filter :logged_in_user
	before_filter :correct_user, only: [:edit, :update, :destroy]
	before_filter :correct_or_admin, only: [:show]
	
	require 'will_paginate/array'
	
	def show
		@applicant=Applicant.where(id: params[:applicant_id]).first
		@internship=@applicant.internships.where(id: params[:id]).first		
		@mode=params[:mode]
	end
	
	def new
		@applicant=current_user
		@internship=@applicant.internships.new
	end
	
	def create
		@applicant=current_user
		@internship=@applicant.internships.new(params[:internship])
		if @internship.save
			render '_additional_information'
		else
			render 'new'
		end		
	end
	
	def edit
		@applicant=Applicant.where(id: params[:applicant_id]).first
		@internship=@applicant.internships.where(id: params[:id]).first
		render '_general_information'
	end
	
	def update
		@applicant=current_user
		step=params[:step].to_i
		@internship=@applicant.internships.where(id: params[:id]).first
				if @internship.update_attributes(params[:internship])
					case step
					when 0
						render '_general_information'
					when 1
						render '_additional_information'
					when 2
						render '_letter_of_recommendation'
					when 3
						render '_emergency_notification'
					when 4
						flash[:success]=["Application created/updated.","You can view/edit/delete your application before submission."]
						redirect_to @applicant
					end
				else
					case step
					when 1
						render '_general_information'
					when 2
						render '_additional_information'
					when 3
						render '_letter_of_recommendation'
					when 4
						render '_emergency_notification'
					end
				end

	end
	
	def destroy
		Internship.find(params[:id]).destroy
		flash[:success]="Successfully deleted."
		redirect_to current_user
	end
	
	def index
		@internships=Internship.all.paginate(page: params[:page], per_page: 15)
	end
	
	def change_status
		@applicant=current_user
		@internship=@applicant.internships.where(id: params[:id]).first
		ApplicantMailer.internship_notification(@applicant,@internship).deliver
		ApplicantMailer.internship_confirmation(@applicant,@internship).deliver
		@internship.update_attributes(params[:status])
		flash[:success]=["Application form submited!","To finish your application, please also complete:", "Intern Agreement.pdf", "Pledge of Confidentiality.pdf", "Non-disclosure Form.pdf", "Background Check.pdf", "which can be found in Resouces tab above and send them to info@scottyshouse.org"]
		redirect_to current_user
	end
	
	def logged_in_user
		unless logged_in?
			store_location
			flash[:danger]="You need to log in."
			redirect_to login_url
		end
	end

	def correct_user
		@internship=Internship.where(id: params[:id]).first
		unless current_user?(@internship.applicant)
			flash[:danger]="Authorization limited."
			redirect_to(root_url)			
		end
	end
	
	def correct_or_admin
		@internship=Internship.where(id: params[:id]).first
		unless ( current_user?(@internship.applicant) || current_user.is_admin? )
			flash[:danger]="Authorization limited."
			redirect_to(root_url)			
		end
	end




end

app/helpers/internships_helper.rb
module InternshipsHelper
end

app/views/internships/_additional_information.html.erb
<h1>Internship/Practicum Application</h1>
<h2>Additional Information</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3 ">
    <%= form_for(@internship) do |f| %>
			<%= render 'shared/error_messages' %>   
            
      <p>Because of the sensitive nature of issues dealt with at Scotty’s House, we strive to place interns in the most appropriate manner possible to meet the needs of the children and families we serve.</p>
      
      <%= f.label :how_hear, "How did you hear about Scotty’s House?" %>
      <%= f.text_area :how_hear, class: 'form-control', rows: "5" %>
      
      <%= f.label :victim, "Have you or a loved one ever been a victim of abuse?" %>
      <%= f.text_area :victim, class: 'form-control', rows: "5" %>
      
      <%= f.label :why_work, "Briefly describe why you would like to work at Scotty’s House:" %>
      <%= f.text_area :why_work, class: 'form-control', rows: "5" %>
      
      <%= f.label :hope_to_do, "What do you hope to do once you have obtained your degree/license? " %>
      <%= f.text_area :hope_to_do, class: 'form-control', rows: "5" %>
      
      <%= f.label :other_language, "List any other languages you speak:" %>
      <%= f.text_field :other_language, class: 'form-control' %>
      
      <%= f.label :other_information, "Please list any other information that may be relevant to your possible internship at SHCAC: " %>
      <%= f.text_area :other_information, class: 'form-control', rows: "5" %>

      <%= f.button  :Previous, name: "step",value: "0", class: "btn btn-warning col-md-2 col-md-offset-3"%>      
      <div></div>
      <%= f.button :Next, name: "step",value: "2", class: "btn btn-primary col-md-2 col-md-offset-2" %>
    <% end %>
  </div>
</div>

app/views/internships/_emergency_notification.html.erb
<h1>Internship/Practicum Application</h1>
<h2>Emergency Notification</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3 ">
    <%= form_for(@internship) do |f| %>
			<%= render 'shared/error_messages' %>   
            
      <p>In case of an emergency while at Scotty’s House Child Advocacy Center, please notify:</p>
 
      <%= f.label :emergency_name, "Name" %>
      <%= f.text_field :emergency_name, class: 'form-control' %>
      
      <%= f.label :emergency_relationship, "Relationship" %>
      <%= f.text_field :emergency_relationship, class: 'form-control' %>
      
      <%= f.label :emergency_phone, "Phone" %>
      <%= f.text_field :emergency_phone, class: 'form-control' %>
      
      <%= f.label :emergency_address, "Address" %>
      <%= f.text_field :emergency_address, class: 'form-control' %>
      
      <%= f.label :emergency_city, "City" %>
      <%= f.text_field :emergency_city, class: 'form-control' %>
      
      <%= f.label :emergency_state, "State" %>
      <%= f.text_field :emergency_state, class: 'form-control' %>
      
      <%= f.label :emergency_zip, "Zip" %>
      <%= f.text_field :emergency_zip, class: 'form-control' %>

      <%= f.button  :Previous, name: "step",value: "2", class: "btn btn-warning col-md-2 col-md-offset-3"%>      
      <div></div>
      <%= f.button :Finish, name: "step",value: "4", class: "btn btn-primary col-md-2 col-md-offset-2" %>
    <% end %>
  </div>
</div>

app/views/internships/_general_information.html.erb
<h1>Internship/Practicum Application</h1>
<h2>General Information</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3 ">
    <%= form_for(@internship) do |f| %>
			<%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
      
      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>
      
      <%= f.label :state %>
      <%= f.text_field :state, class: 'form-control' %>
      
      <%= f.label :zip %>
      <%= f.text_field :zip, class: 'form-control' %>
      
      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control' %>      

      <p>I am a (please check one):</p>      
   
      <%= f.label :counseling_student do %>
      	<%= f.check_box :counseling_student, class: "checkbox-auto" %>
      	<span>Counseling/Psychology Student</span>
      <% end %>
      <br>
      <div style="margin-left:18px;" id="counseling_student" class="hide">
      <%= f.label :university_a, "University" %>
      <%= f.text_field :university_a, class: 'form-control' %>
      
      <%= f.label :supervisor, "University Supervisor" %>
      <%= f.text_field :supervisor, class: 'form-control' %>
      
      <%= f.label :sup_phone, "Phone" %>
      <%= f.text_field :sup_phone, class: 'form-control' %>
      
      <%= f.label :sup_email, "Email" %>
      <%= f.text_field :sup_email, class: 'form-control' %>
   		
   		<%= f.label :graduation_date %>
      <%= f.text_field :graduation_date, class: 'form-control' %>
      
      <%= f.label :commit_two_semester do %>
      	<%= f.check_box :commit_two_semester, class: "checkbox-auto" %>
      	<span>Are you prepared to commit two semesters to Scotty’s House clients?</span>
      <% end %>
      </div>
      
      <%= f.label :LPC_intern do %>
      	<%= f.check_box :LPC_intern, class: "checkbox-auto" %>
      	<span>LPC Intern</span>
      <% end %>
      <br>
      <div style="margin-left:18px;" id="LPC_intern" class="hide">
      <%= f.label :univeristy_b, "University" %>
      <%= f.text_field :univeristy_b , class: 'form-control' %>
      
      <%= f.label :LPC_supervisor, "LPC Supervisor" %>
      <%= f.text_field :LPC_supervisor, class: 'form-control' %>
      
      <%= f.label :LPC_supervisor_phone, "Phone" %>
      <%= f.text_field :LPC_supervisor_phone, class: 'form-control' %>
      
      <%= f.label :LPC_supervisor_email, "Email" %>
      <%= f.text_field :LPC_supervisor_email, class: 'form-control' %>
      
      <%= f.label :commit_one_year do %>
      	<%= f.check_box :commit_one_year, class: "checkbox-auto" %>
      	<span>Are you prepared to commit one year to Scotty’s House clients?</span>
      <% end %>
      </div>
      
      <%= f.label :course_requirement, "Please describe your course or licensure requirements for your practicum/internship below:" %>
      <%= f.text_area :course_requirement, class: 'form-control', rows: "5" %>
      
      <%= f.label :experience_with_children, "Please describe your experience with children:" %>
      <%= f.text_area :experience_with_children, class: 'form-control', rows: "5" %>
      
      <%= hidden_field_tag :step, 1 %>

      <%= f.submit "Next", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<script>
	window.onload = function(){
		c1=document.getElementById("internship_counseling_student");
		c2=document.getElementById("internship_LPC_intern");
		c1.onchange=function(){
			s=document.getElementById("counseling_student")
			if (c1.checked){
				s.setAttribute("class", "");
			} else {
				s.setAttribute("class", "hide");
			}
		}
		c2.onchange=function(){
			s=document.getElementById("LPC_intern")
			if (c2.checked){
				s.setAttribute("class", "");
			} else {
				s.setAttribute("class", "hide");
			}
		}
	}
</script>

app/views/internships/_internship.html.erb
<li class="list-group-item container">
	
	 <% time=internship.created_at.strftime("%d %b %Y")+":" %>
	 <% application='Counseling Internship' %>
	 <% if internship.counseling_student %>
		<% application += " (Counseling Student)" %>
	 <% end %>
	 <% if internship.LPC_intern %>
		<% application += " (LPC Intern)" %>
	 <% end %>
	 <span><%= time %></span>
	 <span><%= application %></span>
	 <br>
	 <%= link_to "View", applicant_internship_path(@applicant, internship, mode: "#{@mode}") %>
	 <% if !current_user.nil? && !current_user.admin? && current_user?(@applicant) && !internship.submited %>
	 	 | <%= link_to "Edit", edit_applicant_internship_path(@applicant, internship) %> 
	 	 | <%= link_to "Delete", applicant_internship_path(@applicant, internship), method: :delete, data: {confirm: "Are you sure?"} %>
	 	 <%= link_to "Submit", change_status_applicant_internship_path(@applicant, internship, status: {submited: true}), method: :put, class: 'pull-right btn btn-warning' %>
	 <% end %>
	
</li>

app/views/internships/_letter_of_recommendation.html.erb
<h1>Internship/Practicum Application</h1>
<h2>Letter of Recommendation</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3 ">
    <%= form_for(@internship) do |f| %>
			<%= render 'shared/error_messages' %>   
            
      <p>Please include a letter/email of recommendation from a university professor other than your university supervisor as well as the personal references below.	</p>
      
      <p>University Professor:</p>      
      
      <%= f.label :reference_name_prof, "Name" %>
      <%= f.text_field :reference_name_prof, class: 'form-control' %>
      
      <%= f.label :reference_phone_prof, "Phone" %>
      <%= f.text_field :reference_phone_prof, class: 'form-control' %>
      
      <%= f.label :relationship_prof, "Relationship" %>
      <%= f.text_field :relationship_prof, class: 'form-control' %>
      
      <%= f.label :how_long_prof, "How long have you known this person?" %>
      <%= f.text_field :how_long_prof, class: 'form-control' %>
      
      <p>Personal References:</p>      
      
      <%= f.label :reference_name_personal, "Name" %>
      <%= f.text_field :reference_name_personal, class: 'form-control' %>
      
      <%= f.label :reference_phone_personal, "Phone" %>
      <%= f.text_field :reference_phone_personal, class: 'form-control' %>
      
      <%= f.label :relationship_personal, "Relationship" %>
      <%= f.text_field :relationship_personal, class: 'form-control' %>
      
      <%= f.label :how_long_personal, "How long have you known this person?" %>
      <%= f.text_field :how_long_personal, class: 'form-control' %>

      <%= f.button  :Previous, name: "step",value: "1", class: "btn btn-warning col-md-2 col-md-offset-3"%>      
      <div></div>
      <%= f.button :Next, name: "step",value: "3", class: "btn btn-primary col-md-2 col-md-offset-2" %>
    <% end %>
  </div>
</div>

app/views/internships/index.html.erb
<h1>Internship Applications List</h1>

<div class="volunteers col-sm-offset-3 col-sm-6"><%= will_paginate %></div>

<ul class="internships col-sm-offset-3 col-sm-6"> 
	<% @internships.each do |internship| %> 
		<li class="list-group-item">
			 <% time=internship.created_at.strftime("%d %b %Y")+":" %>
			 <% application='Counseling Internship' %>
			 <% if internship.counseling_student %>
				<% application += " (Counseling Student)" %>
			 <% end %>
			 <% if internship.LPC_intern %>
				<% application += " (LPC Intern)" %>
			 <% end %>
			 <div style="font-size: 1.8em; ">Applicant: <span class="text-primary"><%= internship.name %></span></div>
			 <div style="font-size: 1.2em;" class="text-primary"><%= time %></div>
			 <div style="font-size: 1.2em;" class="text-success"><%= application %></div>
			 <%= link_to "View", applicant_internship_path(internship.applicant, internship), class: "btn bg-primary " %>
		</li>
	<% end %>
	<br>
	<div class="center"><%= link_to "Go back", applicant_path(current_user), class: "btn btn-lg btn-primary" %></div>
</ul>

app/views/internships/new.html.erb
<h1>Internship/Practicum Application</h1>
<h2>General Information</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3 ">
    <%= form_for(@internship) do |f| %>
			<%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
      
      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>
      
      <%= f.label :state %>
      <%= f.text_field :state, class: 'form-control' %>
      
      <%= f.label :zip %>
      <%= f.text_field :zip, class: 'form-control' %>
      
      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control' %>      

      <p>I am a (please check one):</p>      
   
      <%= f.label :counseling_student do %>
      	<%= f.check_box :counseling_student, class: "checkbox-auto" %>
      	<span>Counseling/Psychology Student</span>
      <% end %>
      <br>
      <div style="margin-left:18px;" id="counseling_student" class="hide">
      <%= f.label :university_a, "University" %>
      <%= f.text_field :university_a, class: 'form-control' %>
      
      <%= f.label :supervisor, "University Supervisor" %>
      <%= f.text_field :supervisor, class: 'form-control' %>
      
      <%= f.label :sup_phone, "Phone" %>
      <%= f.text_field :sup_phone, class: 'form-control' %>
      
      <%= f.label :sup_email, "Email" %>
      <%= f.text_field :sup_email, class: 'form-control' %>
   		
   		<%= f.label :graduation_date %>
      <%= f.text_field :graduation_date, class: 'form-control' %>
      
      <%= f.label :commit_two_semester do %>
      	<%= f.check_box :commit_two_semester, class: "checkbox-auto" %>
      	<span>Are you prepared to commit two semesters to Scotty’s House clients?</span>
      <% end %>
      </div>
      
      <%= f.label :LPC_intern do %>
      	<%= f.check_box :LPC_intern, class: "checkbox-auto" %>
      	<span>LPC Intern</span>
      <% end %>
      <br>
      <div style="margin-left:18px;" id="LPC_intern" class="hide">
      <%= f.label :univeristy_b, "University" %>
      <%= f.text_field :univeristy_b , class: 'form-control' %>
      
      <%= f.label :LPC_supervisor, "LPC Supervisor" %>
      <%= f.text_field :LPC_supervisor, class: 'form-control' %>
      
      <%= f.label :LPC_supervisor_phone, "Phone" %>
      <%= f.text_field :LPC_supervisor_phone, class: 'form-control' %>
      
      <%= f.label :LPC_supervisor_email, "Email" %>
      <%= f.text_field :LPC_supervisor_email, class: 'form-control' %>
      
      <%= f.label :commit_one_year do %>
      	<%= f.check_box :commit_one_year, class: "checkbox-auto" %>
      	<span>Are you prepared to commit one year to Scotty’s House clients?</span>
      <% end %>
      </div>
      
      <%= f.label :course_requirement, "Please describe your course or licensure requirements for your practicum/internship below:" %>
      <%= f.text_area :course_requirement, class: 'form-control', rows: "5" %>
      
      <%= f.label :experience_with_children, "Please describe your experience with children:" %>
      <%= f.text_area :experience_with_children, class: 'form-control', rows: "5" %>
      
      <%= hidden_field_tag :step, 1 %>

      <%= f.submit "Next", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<script>
	window.onload = function(){
		c1=document.getElementById("internship_counseling_student");
		c2=document.getElementById("internship_LPC_intern");
		c1.onchange=function(){
			s=document.getElementById("counseling_student")
			if (c1.checked){
				s.setAttribute("class", "");
			} else {
				s.setAttribute("class", "hide");
			}
		}
		c2.onchange=function(){
			s=document.getElementById("LPC_intern")
			if (c2.checked){
				s.setAttribute("class", "");
			} else {
				s.setAttribute("class", "hide");
			}
		}
	}
</script>

	

app/views/internships/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 ">

		<h1>Internship/Practicum Application</h1>

		<h2>General Information</h2>
		<p>Date of Application: <span><%= @internship.created_at.strftime("%d %b. %Y") %></span></p>
		<p>Name: <span><%= @internship.name %></span></p>
		<p>Address: <span><%= @internship.address %></span></p>
		<p>City: <span><%= @internship.city %></span></p>
		<p>State: <span><%= @internship.state %></span></p>
		<p>Zip: <span><%= @internship.zip %></span></p>
		<p>Phone: <span><%= @internship.phone %></span></p>
		<p>I am a (please check one):</p>
		<% if @internship.counseling_student %>
			<div style="margin-left:18px;">
				<p style="font-weight: bold;">Counseling/Psychology Student</p>
				<p>University: <span><%= @internship.university_a %></span></p>
				<p>University Supervisor: <span><%= @internship.supervisor %></span></p>
				<p>Phone: <span><%= @internship.sup_phone %></span></p>
				<p>Email: <span><%= @internship.sup_email %></span></p>
				<p>Graduation date: <span><%= @internship.graduation_date %></span></p>
				<% if @internship.commit_two_semester %><p>I am prepared to commit two semesters to Scotty’s House clients.</p><% end %>
			</div>
		<% end %>
		<% if @internship.LPC_intern %>
			<div style="margin-left:18px;">
				<p style="font-weight: bold;">LPC Intern</p>
				<p>University: <span><%= @internship.univeristy_b %></span></p>
				<p>LPC Supervisor: <span><%= @internship.LPC_supervisor %></span></p>
				<p>Phone: <span><%= @internship.LPC_supervisor_phone %></span></p>
				<p>LPC supervisor email: <span><%= @internship.LPC_supervisor_email %></span></p>
				<% if @internship.commit_one_year %><p>I am prepared to commit one year to Scotty’s House clients.</p><% end %>
			</div>
		<% end %>
		<p>Please describe your course or licensure requirements for your practicum/internship below: <br><span><%= @internship.course_requirement %></span></p>
		<p>Please describe your experience with children: <br><span><%= @internship.experience_with_children %></span></p>

		
		
		<h2>Additional Information</h2>
		<p>Because of the sensitive nature of issues dealt with at Scotty’s House, we strive to place interns in the most appropriate manner possible to meet the needs of the children and families we serve.</p>
		<p>How did you hear about Scotty’s House? <br><span><%= @internship.how_hear %></span></p>
		<p>Have you or a loved one ever been a victim of abuse? <br><span><%= @internship.victim %></span></p>
		<p>Briefly describe why you would like to work at Scotty’s House: <br><span><%= @internship.why_work %></span></p>
		<p>What do you hope to do once you have obtained your degree/license? <br><span><%= @internship.hope_to_do %></span></p>
		<p>List any other languages you speak: <br><span><%= @internship.other_language %></span></p>
		<p>Please list any other information that may be relevant to your possible internship at SHCAC: <br><span><%= @internship.other_information %></span></p>

		
		
		<h2>Letter of Recommendation</h2>
		<p>Please include a letter/email of recommendation from a university professor other than your university supervisor as well as the personal references below.</p>
		<p style="font-weight: bold;">University Professor:</p>
		<p>Name: <span><%= @internship.reference_name_prof %></span></p>
		<p>Phone: <span><%= @internship.reference_phone_prof %></span></p>
		<p>Relationship: <span><%= @internship.relationship_prof %></span></p>
		<p>How long have you known this person? <span><%= @internship.how_long_prof %></span></p>
		<p style="font-weight: bold;">Personal References:</p>
		<p>Name: <span><%= @internship.reference_name_personal %></span></p>
		<p>Phone: <span><%= @internship.reference_phone_personal %></span></p>
		<p>Relationship: <span><%= @internship.relationship_personal %></span></p>
		<p>How long have you known this person? <span><%= @internship.how_long_personal %></span></p>

		
		<h2>Emergency Notification</h2>
		<p>In case of an emergency while at Scotty’s House Child Advocacy Center, please notify:</p>
		<p>Name: <span><%= @internship.emergency_name %></span></p>
		<p>Relationship: <span><%= @internship.emergency_relationship %></span></p>
		<p>Phone: <span><%= @internship.emergency_phone %></span></p>
		<p>Address: <span><%= @internship.emergency_address %></span></p>
		<p>City: <span><%= @internship.emergency_city %></span></p>
		<p>State: <span><%= @internship.emergency_state %></span></p>
		<p>Zip: <span><%= @internship.emergency_zip %></span></p>
		
		<% if current_user.admin? && @mode!="review" %>
			<div class="center"><%= link_to "Go back", internships_path, class: "btn btn-lg btn-primary" %></div>
		<% else %>
			<div class="center"><%= link_to "Go back", applicant_path(@applicant), class: "btn btn-lg btn-primary" %></div>
		<% end %>
		
	</div>
</div>