config/routes.rb
AppSys::Application.routes.draw do

  root to: 'page#home'
	get 'home' => 'page#home'
  get 'contact' => 'page#contact'
	get 'signup' => 'applicants#new'
	get 'login' => 'sessions#new'
	get 'requirementsc' => 'page#requirementsc'
  get 'requirementsp' => 'page#requirementsp'
  get 'requirementsv' => 'page#requirementsv'
  get 'resources' => 'page#resources'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'

	resources :applicants do
		collection do
			get 'search'
		end
		resources :volunteers do
			member do
				put 'change_status'
			end
		end
		resources :internships do
			member do
				put 'change_status'
			end
		end
	end
	resources :volunteers
	resources :internships
	resources :account_activations, only: [:edit]
	resources :password_resets, only: [:new, :create, :edit, :update]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Scotty's House. 2424 Kent Street Bryan, Texas 77802
  </small>
  <nav>
  	<% if !current_user.nil? && current_user.admin? %>
			<%= link_to "Administrator Interface", applicant_path(current_user), class: "pull-right" %>
		<% end %>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-static-top">
      <div class="container">

        <%= link_to image_tag("0.png", alt: "SH logo"),
            'http://scottyshouse.org/', id: "logo", style: "padding-right:10px; padding-top:15px;" %>
        <img id="1" style="padding-top:27px;" src="/assets/1.png">
        <img id="2" style="padding-top:27px;" src="/assets/2.png">
        <img id="3" style="padding-top:27px;" src="/assets/3.png">
        
        
          <ul class="nav navbar-nav navbar-right" id="nav-bar" style="margin-top:20px;">
            <li><%= link_to "Home",   home_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
						<li><%= link_to "Resources",   resources_path %></li>
					

					<li class="dropdown">
				      <a href="#" class="dropdown-toggle" data-toggle="dropdown"  >Requirement <span class="caret"></span></a>
				      <ul class="dropdown-menu" >
						    <li><%= link_to "Counseling Intern", requirementsc_path %></li>									
							<li><%= link_to "Volunteer", requirementsv_path %></li>
							<li><%= link_to "Program Intern", requirementsp_path %></li>
						  </ul>
				    </li>

					<% if logged_in? %>
						<% if !current_user.admin? %>
						<li class="dropdown">
				     <a href="#" class="dropdown-toggle" data-toggle="dropdown"  >Apply Now <span class="caret"></span></a>
				     <ul class="dropdown-menu" >				    											 								  
								<li><%= link_to "Counseling Intern", new_applicant_internship_path(current_user) %></li>
						    <li><%= link_to "Volunteer", new_applicant_volunteer_path(current_user, type: "volunteer") %></li>
							 <li><%= link_to "Program Intern", new_applicant_volunteer_path(current_user, type: "program") %></li>
								
					   </ul>
				   	</li>
				   	<% end %>
				   <% else %>
				   	<li class="dropdown">
				     <a href="#" class="dropdown-toggle" data-toggle="dropdown"  >Apply Now <span class="caret"></span></a>
				     <ul class="dropdown-menu" >				    											 								  				 
								 <li><%= link_to "Counseling Intern", login_path %></li>  
								 <li><%= link_to "Volunteer", login_path %></li>	
								 <li><%= link_to "Program Intern", login_path %></li>	
					   </ul>
				   	</li>
				   <% end %>


				    <% if logged_in? %>
						  <li class="dropdown">
						    <a href="#" class="dropdown-toggle" data-toggle="dropdown"  ><%= current_user[:name]%> <span class="caret"></span></a>
						    <ul class="dropdown-menu" >
								  <li><%= link_to "View applications", current_user %></li>								 
								  <li><%= link_to "Settings", edit_applicant_path(current_user)%></li>
									<li class="divider"></li>
								  <li><%= link_to "Log out", logout_path, method: "delete" %></li>    
								</ul>
						  </li>
						<% else %>
							<li><%= link_to "Log in", login_path%></li>
						<% end %>
          </ul>
       
      </div>
</header>

<script>
	window.onload=function(){
		var imgs=document.getElementsByTagName("img");
		for (var i=0;i<imgs.length;i++){
			imgs[i].onmouseover=function(e){
				var img=e.target;
				if (img.id==0){
					return;
				}
				if (img.id<3){
					img.id++;
				}else{
					img.id=1;
				}		
				var pic_src="/assets/"+img.id+".png";
				img.src=pic_src;
			};
		}
	}
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <link rel="shortcut icon" href="/assets/1.png"/>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim'%>
  </head>
  <body>
    <%= render 'layouts/header'%>
		<div class="container">
			<% flash.each do |message_type, message| %>
		    <div class="alert alert-<%= message_type %>">
		    	<% if message.is_a?(String)%>
				  	<%= message %>
				  <% else %>
				  	<% message.each do |msg| %>
				  		<%= msg %>
				  		<br>
				  	<% end%>
				  <% end %>
		    </div>
		  <% end %>
		</div>
    <div class="container">
      <%= yield %>			
    </div>
		<div class="container">
		<%= render 'layouts/footer'%>
		</div>
		<%= debug(params) if Rails.env.development? %>
  </body>
</html>